### ISSUE TITLE
As I user, when I go to the  home page. I will see the list of location. After I choose a location, I am move to a new page where I will see the question and 4 options. I choose my answer and  the website will say I am right or wrong

### ISSUE THREAD

**Issue by viettrung2103** [CleanWorldMetro/QuizGame#11]
***Tasks need to be done***

- [x] add route to home page (1h)
- [x] add route to location page (1h)
- [x] add route to question page (1h)
